# Generated by Django 4.0.4 on 2022-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uniprot_id", models.CharField(max_length=20)),
                ("annotation", models.TextField()),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "uniprot_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
                ),
                ("sequence", models.TextField()),
                ("secondary_structure", models.TextField()),
            ],
        ),
    ]
